title: Hardik's Blog
email: 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joghar.github.io"

# url
blogs_url: "/blogs"
about_url: "/about"
back_home: "/"
rss_url: "/rss.xml"

github_username: joghar

feed:
  path: rss.xml

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: compressed