title: Hardik Jogani
email: joganihardik57@gmail.com
baseurl: "/"
url: "https://joghar.github.io"
github_link: https://github.com/joghar/
linkedin_link: https://in.linkedin.com/in/joghar

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

feed:
  path: rss.xml

permalink: /blog/:title
issues_repo: joghar/comment_repo

excerpt_separator: <!--more-->
