title: Hardik Jogani
email: joganihardik57@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://joghar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

feed:
  path: rss.xml

permalink: /:year/:month/:day/:title

excerpt_separator: <!--more-->