title: Hardik's Blog
email: 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joghar.github.io"

# url
blogs_url: "/blogs"
back_home: "/"
rss_url: "/rss.xml"

name: Hardik Jogani
intro: Java and Angular Developer

github_username: joghar
mail_id: joganihardik57@gmail.com

feed:
  path: rss.xml

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: compressed
